version: '3.8'

services:
  disvox_db:
    container_name: disvox_db
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: disvox
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 5s
      timeout: 10s
      retries: 10
    volumes:
      - disvox_data:/var/lib/mysql
    ports:
      - '3309:3306'
    networks:
      - disvox

volumes:
  disvox_data:

networks:
  disvox:
    driver: bridge
