version: '3.8'

services:
  disvox_db:
    image: postgres:latest
    container_name: disvox_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: disvox
    volumes:
      - disvox_data:/var/lib/postgresql/data
    networks:
      - disvox

volumes:
  disvox_data:

networks:
  disvox:
    driver: bridge
