services:
  disvox_db:
    image: postgres:latest
    container_name: disvox_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: disvox
    volumes:
      - disvox_data:/var/lib/postgresql/data

  # bytebase:
  #   image: bytebase/bytebase:2.13.1
  #   container_name: bytebase
  #   ports:
  #     - '8080:8080'
  #   volumes:
  #     - ~/.bytebase/data:/var/opt/bytebase
  #   init: true

volumes:
  disvox_data:
